@file:OptIn(androidx.compose.material3.ExperimentalMaterial3Api::class)

package com.example.dam_front.ui.screens

import android.app.DatePickerDialog
import android.net.Uri
import androidx.activity.ComponentActivity
import androidx.activity.compose.rememberLauncherForActivityResult
import androidx.activity.result.contract.ActivityResultContracts
import androidx.compose.foundation.background
import androidx.compose.foundation.border
import androidx.compose.foundation.BorderStroke
import androidx.compose.foundation.clickable
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.items
import androidx.compose.foundation.shape.CircleShape
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.*
import androidx.compose.material.icons.automirrored.filled.DirectionsRun
import androidx.compose.material.icons.automirrored.filled.TrendingUp
import androidx.compose.material.icons.automirrored.outlined.Logout
import androidx.compose.material.icons.outlined.Logout
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.material3.FilterChip
import androidx.compose.material3.FilterChipDefaults
import androidx.compose.runtime.rememberCoroutineScope
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.clip
import androidx.compose.ui.draw.shadow
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.Brush
import androidx.compose.ui.layout.ContentScale
import androidx.compose.ui.platform.LocalClipboardManager
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.text.AnnotatedString
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.text.style.TextOverflow
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import androidx.compose.ui.window.DialogProperties
import androidx.lifecycle.viewmodel.compose.viewModel as composeViewModel
import androidx.navigation.NavController
import androidx.navigation.compose.NavHost
import androidx.navigation.compose.composable
import androidx.navigation.compose.rememberNavController
import coil.compose.AsyncImage
import coil.request.ImageRequest
import kotlinx.coroutines.launch
import android.util.Log
import com.example.dam_front.config.ApiConfig
import com.example.dam_front.data.SuiviEnfant
import com.example.dam_front.models.CreateChildRequest
import com.example.dam_front.repository.AuthRepository
import com.example.dam_front.utils.ImageUtils
import com.example.dam_front.ui.theme.*
import com.example.dam_front.viewmodels.ParentHomeViewModel
import com.example.dam_front.viewmodels.SuiviSharedViewModel
import com.example.dam_front.viewmodels.SuiviSharedViewModelFactory
import kotlinx.coroutines.launch
import java.text.SimpleDateFormat
import java.util.Calendar
import java.util.Locale

const val PRESENCE_DETAIL_ROUTE = "presence_detail"

@Composable
fun ParentScreen(navController: NavController, vm: ParentHomeViewModel, onLogout: () -> Unit = { Log.w("ParentScreen", "DEFAULT LOGOUT CALLED - NO REAL CALLBACK PROVIDED!") }) {
    Log.d("ParentScreen", "ParentScreen created. Testing onLogout callback immediately...")
    // Test the callback to make sure it's working
    LaunchedEffect(Unit) {
        Log.d("ParentScreen", "Callback test - this should trigger MainActivity logout if working properly")
        // Don't actually call onLogout here, just log that we could
    }
    val uiState by vm.uiState.collectAsState()
    val snackbarHostState = remember { SnackbarHostState() }
    val context = LocalContext.current

    // Shared ViewModel for Suivis
    val activity = LocalContext.current as ComponentActivity
    val application = LocalContext.current.applicationContext as android.app.Application
    val sharedVm: SuiviSharedViewModel = composeViewModel(
        viewModelStoreOwner = activity,
        factory = SuiviSharedViewModelFactory(application)
    )
    val suivisMap by sharedVm.suivisByChild.collectAsState()

    // Local State
    var searchQuery by remember { mutableStateOf("") }
    var showCreateDialog by remember { mutableStateOf(false) }
    var showGenerated by remember { mutableStateOf<Pair<String, String>?>(null) }
    var selectedChildId by remember { mutableStateOf("") }

    // Get parent info
    var parentName by remember { mutableStateOf("") }
    var parentPhoto by remember { mutableStateOf<String?>(null) }

    LaunchedEffect(Unit) {
        kotlinx.coroutines.delay(500)
        vm.loadData()

        // Get parent info
        try {
            val authRepo = AuthRepository(context)
            val userId = authRepo.getUserId()
            if (!userId.isNullOrBlank()) {
                val user = authRepo.getUser(userId)
                parentName = listOfNotNull(user.prenom, user.nom).joinToString(" ").ifBlank { user.email ?: "Parent" }
                parentPhoto = user.photoProfil
            }
        } catch (e: Exception) {
            parentName = "Parent"
        }
    }

    // Load and refresh suivis
    LaunchedEffect(Unit) {
        sharedVm.loadAllSuivis()
    }

    // Also refresh when child selection changes to be sure
    LaunchedEffect(selectedChildId) {
        if (selectedChildId.isNotEmpty()) {
            sharedVm.refreshForChild(selectedChildId)
        } else {
            sharedVm.loadAllSuivis()
        }
    }

    // Get all suivis and filter
    val allSuivis = remember(suivisMap, selectedChildId) {
        // Flatten all lists and remove duplicates based on suivi ID
        val allList = suivisMap.values.flatten().distinctBy { it.id }

        if (selectedChildId.isBlank()) {
            allList
        } else {
            // Filter by selected child ID
            allList.filter {
                val childId = it.enfant?.id ?: it.enfantId
                childId == selectedChildId
            }
        }
    }.sortedByDescending { it.dateSuivi }

    val filteredSuivis = remember(allSuivis, searchQuery) {
        if (searchQuery.isBlank()) {
            allSuivis
        } else {
            allSuivis.filter { suivi ->
                val childName = suivi.enfant?.let { "${it.prenom} ${it.nom}" } ?: suivi.enfantName ?: ""
                childName.contains(searchQuery, ignoreCase = true)
            }
        }
    }

    Scaffold(
        snackbarHost = { SnackbarHost(snackbarHostState) },
        containerColor = Color.Transparent,
        modifier = Modifier.fillMaxSize(),
        floatingActionButton = {
            FloatingActionButton(
                onClick = { navController.navigate("chat_list") },
                containerColor = HeaderBlue,
                contentColor = Color.White,
                shape = CircleShape
            ) {
                Icon(
                    imageVector = Icons.Default.ChatBubble,
                    contentDescription = "Chat",
                    modifier = Modifier.size(24.dp)
                )
            }
        }
    ) { innerPadding ->
        Column(
            modifier = Modifier
                .fillMaxSize()
                .padding(innerPadding)
        ) {
            // Simple Top Bar removed to avoid duplication with MainScreen header

            // Action Section
            // Action Section
            ParentActionSection(
                searchQuery = searchQuery,
                onSearchChange = { searchQuery = it },
                children = uiState.children,
                selectedChildId = selectedChildId,
                onChildSelect = { selectedChildId = it },
                onRefresh = {
                    sharedVm.loadAllSuivis()
                    vm.loadData()
                },
                onAiSummaryClick = {
                    if (selectedChildId.isNotEmpty()) {
                        navController.navigate("ai_summary/$selectedChildId")
                    }
                }
            )

            // Suivis List
            if (filteredSuivis.isEmpty()) {
                Box(
                    modifier = Modifier.fillMaxSize(),
                    contentAlignment = Alignment.Center
                ) {
                    Text(
                        "Aucun suivi disponible",
                        color = Color.Gray,
                        fontSize = 16.sp
                    )
                }
            } else {
                LazyColumn(
                    modifier = Modifier
                        .fillMaxSize()
                        .padding(horizontal = 16.dp),
                    verticalArrangement = Arrangement.spacedBy(16.dp),
                    contentPadding = PaddingValues(top = 16.dp, bottom = 80.dp)
                ) {
                    items(filteredSuivis) { suivi ->
                        // Find the child from the children list to get their photo
                        val childId = suivi.enfant?.id ?: suivi.enfantId
                        val child = uiState.children.find { it.id == childId }

                        SuiviCard(
                            suivi = suivi,
                            childPhoto = child?.photoProfil,
                            onDetailsClick = {
                                childId?.let { navController.navigate("$PRESENCE_DETAIL_ROUTE/$it") }
                            },
                            onAiSummaryClick = {
                                childId?.let { navController.navigate("ai_summary/$it") }
                            }
                        )
                    }
                }
            }
        }
    }

    // Dialogs
    if (showCreateDialog) {
        CreateChildDialog(
            onDismiss = { showCreateDialog = false },
            onCreated = { credentials ->
                showCreateDialog = false
                if (credentials != null) {
                    showGenerated = credentials
                    vm.loadData()
                } else {
                    vm.loadData()
                }
            },
            snackbarHostState = snackbarHostState,
            vm = vm
        )
    }

    showGenerated?.let { credentials ->
        val clipboardManager = LocalClipboardManager.current
        AlertDialog(
            onDismissRequest = { showGenerated = null },
            title = { Text("Identifiants générés", color = TextBlue) },
            text = {
                Column {
                    Text("Email: ${credentials.first}")
                    Spacer(Modifier.height(8.dp))
                    Text("Mot de passe: ${credentials.second}")
                }
            },
            confirmButton = {
                Button(onClick = {
                    clipboardManager.setText(AnnotatedString("Email: ${credentials.first}\nMot de passe: ${credentials.second}"))
                }) {
                    Text("Copier")
                }
            },
            dismissButton = {
                TextButton(onClick = { showGenerated = null }) { Text("Fermer") }
            }
        )
    }
}

@Composable
fun SimpleTopBar(
    title: String,
    subtitle: String,
    profilePhoto: String?,
    onLogout: () -> Unit,
    showMenu: Boolean = false,
    onMenuToggle: () -> Unit = {},
    showCreateDialog: Boolean = false,
    onShowCreateDialog: (Boolean) -> Unit = {}
) {
    var localShowMenu by remember { mutableStateOf(false) }
    val context = LocalContext.current
    val coroutineScope = rememberCoroutineScope()


    Row(
        modifier = Modifier
            .fillMaxWidth()
            .background(
                brush = androidx.compose.ui.graphics.Brush.horizontalGradient(
                    colors = listOf(HeaderBlue, HeaderBlueLight)
                )
            )
            .padding(16.dp),
        verticalAlignment = Alignment.CenterVertically
    ) {
        // Profile Photo
        val photoUrl = ImageUtils.getPhotoUrl(profilePhoto) ?: "https://via.placeholder.com/128"

        Box {
            AsyncImage(
                model = ImageRequest.Builder(context).data(photoUrl).crossfade(true).build(),
                contentDescription = "Profile Photo",
                modifier = Modifier
                    .size(40.dp)
                    .clip(CircleShape)
                    .border(1.dp, Color.White.copy(alpha = 0.5f), CircleShape)
                    .clickable { localShowMenu = !localShowMenu },
                contentScale = ContentScale.Crop
            )

            DropdownMenu(
                expanded = localShowMenu,
                onDismissRequest = { localShowMenu = false },
                modifier = Modifier
                    .background(Color.White, RoundedCornerShape(8.dp))
                    .width(200.dp)
            ) {
                DropdownMenuItem(
                    text = { Text("Accueil", color = TextBlue) },
                    onClick = {
                        localShowMenu = false
                        // Navigate to home
                    },
                    leadingIcon = {
                        Icon(Icons.Default.Home, contentDescription = null, tint = HeaderBlue)
                    }
                )
                DropdownMenuItem(
                    text = { Text("Tournois", color = TextBlue) },
                    onClick = {
                        localShowMenu = false
                        // Navigate to tournaments
                    },
                    leadingIcon = {
                        Icon(Icons.Default.EmojiEvents, contentDescription = null, tint = SportyKidsGreen)
                    }
                )
                DropdownMenuItem(
                    text = { Text("Activités", color = TextBlue) },
                    onClick = {
                        localShowMenu = false
                        // Navigate to activities
                    },
                    leadingIcon = {
                        Icon(Icons.AutoMirrored.Filled.DirectionsRun, contentDescription = null, tint = IconOrange)
                    }
                )
                DropdownMenuItem(
                    text = { Text("Progrès", color = TextBlue) },
                    onClick = {
                        localShowMenu = false
                        // Navigate to progress
                    },
                    leadingIcon = {
                        Icon(Icons.AutoMirrored.Filled.TrendingUp, contentDescription = null, tint = SportyKidsGreen)
                    }
                )
                DropdownMenuItem(
                    text = { Text("Mon Enfant", color = TextBlue) },
                    onClick = {
                        localShowMenu = false
                        // Navigate to child profile
                    },
                    leadingIcon = {
                        Icon(Icons.Default.Groups, contentDescription = null, tint = HeaderBlue)
                    }
                )
                DropdownMenuItem(
                    text = { Text("Ajouter un enfant", color = TextBlue) },
                    onClick = {
                        localShowMenu = false
                        onShowCreateDialog(true)
                    },
                    leadingIcon = {
                        Icon(Icons.Default.PersonAdd, contentDescription = null, tint = HeaderBlue)
                    }
                )
                HorizontalDivider()
                DropdownMenuItem(
                    text = { Text("Paramètres", color = TextBlue) },
                    onClick = {
                        localShowMenu = false
                        // Navigate to settings
                    },
                    leadingIcon = {
                        Icon(Icons.Default.Settings, contentDescription = null, tint = HeaderBlue)
                    }
                )
                DropdownMenuItem(
                    text = { Text("Déconnexion", color = SportyKidsRed) },
                    onClick = {
                        localShowMenu = false
                        Log.d("ParentScreen", "=== LOGOUT BUTTON CLICKED ===")
                        Log.d("ParentScreen", "About to call onLogout() callback")
                        try {
                            onLogout()
                            Log.d("ParentScreen", "onLogout() callback completed successfully")
                        } catch (e: Exception) {
                            Log.e("ParentScreen", "Error calling onLogout()", e)
                        }
                    },
                    leadingIcon = {
                        Icon(Icons.AutoMirrored.Outlined.Logout, contentDescription = null, tint = SportyKidsRed)
                    }
                )
            }
        }

        Spacer(Modifier.width(12.dp))

        Column(modifier = Modifier.weight(1f)) {
            Text(
                title,
                color = Color.White,
                fontWeight = FontWeight.Bold,
                fontSize = 18.sp
            )
            Text(
                subtitle,
                color = Color.White.copy(alpha = 0.9f),
                fontSize = 14.sp
            )
        }

        // Notification Icon
        IconButton(onClick = { }) {
            Icon(
                Icons.Default.Notifications,
                contentDescription = "Notifications",
                tint = Color.White,
                modifier = Modifier.size(24.dp)
            )
        }


    }
}

@Composable
fun ParentActionSection(
    searchQuery: String,
    onSearchChange: (String) -> Unit,
    children: List<com.example.dam_front.models.User>,
    selectedChildId: String,
    onChildSelect: (String) -> Unit,
    onRefresh: () -> Unit = {},
    onAiSummaryClick: () -> Unit = {}
) {
    var showFilterDialog by remember { mutableStateOf(false) }

    // Filter Dialog
    if (showFilterDialog) {
        ChildFilterDialog(
            children = children,
            selectedChildId = selectedChildId,
            onChildSelect = {
                onChildSelect(it)
                showFilterDialog = false
            },
            onDismiss = { showFilterDialog = false }
        )
    }

    Column(
        modifier = Modifier
            .fillMaxWidth()
            .background(CardWhite)
            .padding(16.dp)
    ) {
        // Row combining Search, Refresh and Filter
        Row(
            modifier = Modifier.fillMaxWidth(),
            verticalAlignment = Alignment.CenterVertically,
            horizontalArrangement = Arrangement.spacedBy(8.dp)
        ) {
            // Search Bar
            Surface(
                modifier = Modifier.weight(1f),
                shape = RoundedCornerShape(12.dp),
                color = Color(0xFFF5F5F5),
                shadowElevation = 0.dp
            ) {
                TextField(
                    value = searchQuery,
                    onValueChange = onSearchChange,
                    placeholder = { Text("Rechercher...", color = Color.Gray.copy(alpha = 0.6f)) },
                    leadingIcon = {
                        Icon(
                            Icons.Default.Search,
                            contentDescription = null,
                            tint = Color.Gray
                        )
                    },
                    colors = TextFieldDefaults.colors(
                        focusedContainerColor = Color.Transparent,
                        unfocusedContainerColor = Color.Transparent,
                        focusedIndicatorColor = Color.Transparent,
                        unfocusedIndicatorColor = Color.Transparent
                    ),
                    modifier = Modifier.fillMaxWidth(),
                    singleLine = true
                )
            }

            // Refresh Button
            IconButton(
                onClick = onRefresh,
                modifier = Modifier.size(40.dp)
            ) {
                Icon(
                    Icons.Default.Refresh,
                    contentDescription = "Rafraîchir",
                    tint = SportyKidsBlue,
                    modifier = Modifier.size(24.dp)
                )
            }

            // Filter Icon
            IconButton(
                onClick = { showFilterDialog = true },
                modifier = Modifier
                    .size(40.dp)
                    .background(
                        color = if (selectedChildId.isNotEmpty()) SportyKidsGreen.copy(alpha = 0.2f) else Color.Transparent,
                        shape = RoundedCornerShape(12.dp)
                    )
            ) {
                Icon(
                    Icons.Default.FilterList,
                    contentDescription = "Filtrer",
                    tint = if (selectedChildId.isNotEmpty()) SportyKidsGreen else SportyKidsBlue,
                    modifier = Modifier.size(24.dp)
                )
            }

            // AI Summary Icon
            if (selectedChildId.isNotEmpty()) {
                IconButton(
                    onClick = onAiSummaryClick,
                    modifier = Modifier
                        .size(40.dp)
                        .background(
                            color = SportyKidsGreen.copy(alpha = 0.1f),
                            shape = RoundedCornerShape(12.dp)
                        )
                ) {
                    Icon(
                        Icons.Default.AutoAwesome,
                        contentDescription = "Résumé IA",
                        tint = SportyKidsGreen,
                        modifier = Modifier.size(24.dp)
                    )
                }
            }
        }
    }
}

@OptIn(ExperimentalMaterial3Api::class)
@Composable
private fun ChildFilterDialog(
    children: List<com.example.dam_front.models.User>,
    selectedChildId: String,
    onChildSelect: (String) -> Unit,
    onDismiss: () -> Unit
) {
    AlertDialog(
        onDismissRequest = onDismiss,
        title = { Text("Filtrer par enfant", color = HeaderBlue, fontWeight = FontWeight.Bold) },
        text = {
            LazyColumn(
                modifier = Modifier.heightIn(max = 300.dp),
                verticalArrangement = Arrangement.spacedBy(8.dp)
            ) {
                item {
                    FilterChip(
                        selected = selectedChildId.isEmpty(),
                        onClick = { onChildSelect("") },
                        label = { Text("Tous les enfants") },
                        colors = FilterChipDefaults.filterChipColors(
                            selectedContainerColor = IconOrange.copy(alpha = 0.2f),
                            selectedLabelColor = IconOrange
                        )
                    )
                }
                items(children) { child ->
                    FilterChip(
                        selected = selectedChildId == child.id,
                        onClick = { onChildSelect(child.id ?: "") },
                        label = { Text("${child.prenom} ${child.nom}") },
                        colors = FilterChipDefaults.filterChipColors(
                            selectedContainerColor = IconOrange.copy(alpha = 0.2f),
                            selectedLabelColor = IconOrange
                        )
                    )
                }
            }
        },
        confirmButton = {
            TextButton(onClick = onDismiss) {
                Text("Fermer", color = TextDarkGray)
            }
        },
        containerColor = Color.White,
        shape = RoundedCornerShape(16.dp)
    )
}

@Composable
fun SuiviCard(
    suivi: SuiviEnfant,
    childPhoto: String? = null,
    onDetailsClick: () -> Unit,
    onAiSummaryClick: () -> Unit = {}
) {
    val childName = suivi.enfant?.let { "${it.prenom} ${it.nom}" } ?: suivi.enfantName ?: "Élève"
    val sdf = remember { SimpleDateFormat("dd MMM yyyy", Locale.FRANCE) }
    val dateStr = suivi.dateSuivi?.let { sdf.format(it) } ?: "Date inconnue"

    val perfFloat = suivi.performance.toFloat().coerceIn(0f, 10f)
    val perfColor = when {
        perfFloat >= 8f -> SportyKidsGreen
        perfFloat >= 5f -> IconOrange
        else -> SportyKidsRed
    }

    Card(
        modifier = Modifier
            .fillMaxWidth()
            .shadow(12.dp, RoundedCornerShape(28.dp), spotColor = HeaderBlue.copy(alpha = 0.2f)),
        shape = RoundedCornerShape(28.dp),
        colors = CardDefaults.cardColors(containerColor = Color.White)
    ) {
        Column(modifier = Modifier.padding(20.dp)) {
            // Header: Profile & Status
            Row(
                verticalAlignment = Alignment.CenterVertically,
                modifier = Modifier.fillMaxWidth()
            ) {
                val photoUrl = ImageUtils.getPhotoUrl(childPhoto)
                    ?: "https://ui-avatars.com/api/?name=${childName.replace(" ", "+")}&background=4A90E2&color=fff"

                // Avatar with premium ring
                Box(
                    modifier = Modifier
                        .size(60.dp)
                        .background(
                            brush = Brush.linearGradient(colors = listOf(HeaderBlue, IconOrange, SportyKidsGreen)),
                            shape = CircleShape
                        )
                        .padding(2.dp)
                ) {
                    AsyncImage(
                        model = ImageRequest.Builder(LocalContext.current).data(photoUrl).crossfade(true).build(),
                        contentDescription = "Photo de $childName",
                        modifier = Modifier
                            .fillMaxSize()
                            .clip(CircleShape)
                            .background(Color.White, CircleShape),
                        contentScale = ContentScale.Crop
                    )
                }

                Spacer(Modifier.width(16.dp))

                Column(modifier = Modifier.weight(1f)) {
                    Text(
                        childName,
                        fontWeight = FontWeight.ExtraBold,
                        fontSize = 18.sp,
                        color = TextBlue
                    )
                    Text(
                        dateStr,
                        color = Color.Gray,
                        fontSize = 12.sp,
                        fontWeight = FontWeight.Medium
                    )
                }

                // Trophy for High Performance
                if (perfFloat >= 8f) {
                    Surface(
                        color = Color(0xFFFFF9C4),
                        shape = CircleShape,
                        modifier = Modifier.size(36.dp)
                    ) {
                        Box(contentAlignment = Alignment.Center) {
                            Icon(Icons.Default.EmojiEvents, "Trophy", tint = Color(0xFFFBC02D), modifier = Modifier.size(20.dp))
                        }
                    }
                }
            }

            Spacer(Modifier.height(20.dp))

            // Metrics visualization
            Row(
                modifier = Modifier.fillMaxWidth(),
                horizontalArrangement = Arrangement.spacedBy(12.dp)
            ) {
                // Performance Gauge
                Surface(
                    modifier = Modifier.weight(1f),
                    color = Color(0xFFF8FAFC),
                    shape = RoundedCornerShape(20.dp),
                    border = BorderStroke(1.dp, Color(0xFFF1F5F9))
                ) {
                    Column(modifier = Modifier.padding(12.dp)) {
                        Row(verticalAlignment = Alignment.CenterVertically) {
                            Icon(Icons.Default.TrendingUp, null, modifier = Modifier.size(14.dp), tint = perfColor)
                            Spacer(Modifier.width(6.dp))
                            Text("Performance", fontSize = 11.sp, fontWeight = FontWeight.Bold, color = Color.Gray)
                        }
                        Spacer(Modifier.height(8.dp))
                        Row(verticalAlignment = Alignment.Bottom) {
                            Text(perfFloat.toInt().toString(), fontSize = 24.sp, fontWeight = FontWeight.Black, color = TextBlue)
                            Text("/10", fontSize = 14.sp, fontWeight = FontWeight.Bold, color = Color.Gray, modifier = Modifier.padding(bottom = 3.dp))
                        }
                        Spacer(Modifier.height(8.dp))
                        LinearProgressIndicator(
                            progress = perfFloat / 10f,
                            modifier = Modifier.fillMaxWidth().height(6.dp).clip(CircleShape),
                            color = perfColor,
                            trackColor = perfColor.copy(alpha = 0.1f)
                        )
                    }
                }

                // Presence / Status Card
                Surface(
                    modifier = Modifier.weight(1f),
                    color = (if (suivi.presence) Color(0xFFE8F5E9) else Color(0xFFFFEBEE)).copy(alpha = 0.5f),
                    shape = RoundedCornerShape(20.dp),
                    border = BorderStroke(1.dp, (if (suivi.presence) Color(0xFFC8E6C9) else Color(0xFFFFCDD2)))
                ) {
                    Column(modifier = Modifier.padding(12.dp), horizontalAlignment = Alignment.CenterHorizontally, verticalArrangement = Arrangement.Center) {
                        Icon(
                            if (suivi.presence) Icons.Default.CheckCircle else Icons.Default.Cancel,
                            null,
                            modifier = Modifier.size(28.dp),
                            tint = if (suivi.presence) Color(0xFF2E7D32) else Color(0xFFC62828)
                        )
                        Spacer(Modifier.height(8.dp))
                        Text(
                            if (suivi.presence) "PRÉSENT" else "ABSENT",
                            fontWeight = FontWeight.Black,
                            fontSize = 12.sp,
                            color = if (suivi.presence) Color(0xFF2E7D32) else Color(0xFFC62828)
                        )
                        Text("à la séance", fontSize = 10.sp, color = Color.Gray)
                    }
                }
            }

            // Comment Insight
            if (!suivi.commentaire.isNullOrBlank()) {
                Spacer(Modifier.height(16.dp))
                Surface(
                    color = Color(0xFFF1F5F9).copy(alpha = 0.5f),
                    shape = RoundedCornerShape(16.dp)
                ) {
                    Row(modifier = Modifier.padding(12.dp), verticalAlignment = Alignment.Top) {
                        Icon(Icons.Default.Notes, null, modifier = Modifier.size(16.dp), tint = HeaderBlue)
                        Spacer(Modifier.width(10.dp))
                        Text(
                            suivi.commentaire!!,
                            fontSize = 13.sp,
                            color = Color(0xFF475569),
                            lineHeight = 18.sp,
                            fontStyle = androidx.compose.ui.text.font.FontStyle.Italic
                        )
                    }
                }
            }

            Spacer(Modifier.height(24.dp))

            // Action Buttons
            Row(
                modifier = Modifier.fillMaxWidth(),
                horizontalArrangement = Arrangement.spacedBy(10.dp)
            ) {
                Button(
                    onClick = onAiSummaryClick,
                    modifier = Modifier.weight(1.3f).height(48.dp),
                    shape = RoundedCornerShape(16.dp),
                    colors = ButtonDefaults.buttonColors(containerColor = SportyKidsGreen)
                ) {
                    Icon(Icons.Default.AutoAwesome, null, modifier = Modifier.size(18.dp))
                    Spacer(Modifier.width(8.dp))
                    Text("Résumé IA", fontWeight = FontWeight.Bold, fontSize = 14.sp)
                }

                OutlinedButton(
                    onClick = onDetailsClick,
                    modifier = Modifier.weight(1f).height(48.dp),
                    shape = RoundedCornerShape(16.dp),
                    border = BorderStroke(1.5.dp, HeaderBlue),
                    colors = ButtonDefaults.outlinedButtonColors(contentColor = HeaderBlue)
                ) {
                    Text("Détails", fontWeight = FontWeight.Bold, fontSize = 14.sp)
                }
            }
        }
    }
}

@Composable
private fun CreateChildDialog(
    onDismiss: () -> Unit,
    onCreated: (Pair<String, String>) -> Unit,
    snackbarHostState: SnackbarHostState,
    vm: ParentHomeViewModel
) {
    val context = LocalContext.current
    val scope = rememberCoroutineScope()
    var nom by remember { mutableStateOf("") }
    var prenom by remember { mutableStateOf("") }
    val calendar = Calendar.getInstance()
    val dateFormatter = remember { SimpleDateFormat("yyyy-MM-dd", Locale.US) }
    var dateStr by remember { mutableStateOf<String?>(null) }
    var sport by remember { mutableStateOf("") }
    var expandedSport by remember { mutableStateOf(false) }
    val availableSports = listOf(
        "football", "basketball", "tennis", "natation", "volleyball",
        "handball", "rugby", "judo", "karate", "athletisme",
        "gymnastique", "escalade", "cyclisme"
    )
    var isCreating by remember { mutableStateOf(false) }
    var photoUrl by remember { mutableStateOf<String?>(null) }
    var photoUri by remember { mutableStateOf<Uri?>(null) }
    val pickImageLauncher = rememberLauncherForActivityResult(
        contract = ActivityResultContracts.GetContent()
    ) { uri -> photoUri = uri }

    AlertDialog(
        onDismissRequest = { if (!isCreating) onDismiss() },
        title = {
            Column {
                Text("Ajouter un enfant", color = DotGreen, fontWeight = FontWeight.SemiBold)
                Spacer(Modifier.height(4.dp))
                Text(
                    "Les identifiants seront générés automatiquement.",
                    fontSize = 12.sp,
                    color = IconInactiveGray
                )
            }
        },
        text = {
            Column {
                OutlinedTextField(
                    value = nom,
                    onValueChange = { nom = it },
                    label = { Text("Nom") },
                    singleLine = true,
                    modifier = Modifier.fillMaxWidth()
                )
                Spacer(Modifier.height(8.dp))
                OutlinedTextField(
                    value = prenom,
                    onValueChange = { prenom = it },
                    label = { Text("Prénom") },
                    singleLine = true,
                    modifier = Modifier.fillMaxWidth()
                )
                Spacer(Modifier.height(8.dp))
                OutlinedTextField(
                    value = dateStr ?: "Sélectionner la date de naissance",
                    onValueChange = {},
                    readOnly = true,
                    trailingIcon = {
                        IconButton(onClick = {
                            DatePickerDialog(
                                context,
                                { _, y, m, d ->
                                    calendar.set(y, m, d)
                                    dateStr = dateFormatter.format(calendar.time)
                                },
                                calendar.get(Calendar.YEAR),
                                calendar.get(Calendar.MONTH),
                                calendar.get(Calendar.DAY_OF_MONTH)
                            ).show()
                        }) {
                            Icon(Icons.Default.CalendarToday, contentDescription = null, tint = SportyKidsGreen)
                        }
                    },
                    label = { Text("Date de naissance") },
                    singleLine = true,
                    modifier = Modifier.fillMaxWidth()
                )
                Spacer(Modifier.height(8.dp))
                ExposedDropdownMenuBox(
                    expanded = expandedSport,
                    onExpandedChange = { expandedSport = !expandedSport }
                ) {
                    OutlinedTextField(
                        value = sport,
                        onValueChange = {},
                        readOnly = true,
                        label = { Text("Sport pratiqué *") },
                        trailingIcon = {
                            Icon(
                                imageVector = if (expandedSport) Icons.Default.ArrowDropUp else Icons.Default.ArrowDropDown,
                                contentDescription = null
                            )
                        },
                        modifier = Modifier
                            .fillMaxWidth()
                            .menuAnchor()
                    )
                    ExposedDropdownMenu(
                        expanded = expandedSport,
                        onDismissRequest = { expandedSport = false }
                    ) {
                        availableSports.forEach { sportOption ->
                            DropdownMenuItem(
                                text = { Text(sportOption.replaceFirstChar { if (it.isLowerCase()) it.titlecase(Locale.getDefault()) else it.toString() }) },
                                onClick = {
                                    sport = sportOption
                                    expandedSport = false
                                }
                            )
                        }
                    }
                }
                Spacer(Modifier.height(8.dp))
                OutlinedTextField(
                    value = photoUrl ?: "",
                    onValueChange = { photoUrl = it.takeIf { s -> s.isNotBlank() } ?: null },
                    label = { Text("URL photo (optionnelle)") },
                    singleLine = true,
                    modifier = Modifier.fillMaxWidth()
                )
                Spacer(Modifier.height(8.dp))
                Row(verticalAlignment = Alignment.CenterVertically) {
                    Button(
                        onClick = { pickImageLauncher.launch("image/*") },
                        colors = ButtonDefaults.buttonColors(containerColor = Color(0xFFE8F5E8))
                    ) {
                        Text("Choisir une photo", color = SportyKidsGreen)
                    }
                    Spacer(Modifier.width(12.dp))
                    Text("ou coller une URL ci-dessous", color = IconInactiveGray, fontSize = 12.sp)
                }
            }
        },
        confirmButton = {
            val enabled = nom.isNotBlank() && prenom.isNotBlank() && !dateStr.isNullOrBlank() && sport.isNotBlank() && !isCreating
            Button(
                onClick = {
                    scope.launch {
                        isCreating = true
                        try {
                            val authRepo = AuthRepository(context)
                            var pid = authRepo.getUserId()
                            var waited = 0
                            while (pid.isNullOrBlank() && waited < 5000) {
                                kotlinx.coroutines.delay(300)
                                waited += 300
                                pid = authRepo.getUserId()
                            }
                            if (pid.isNullOrBlank()) {
                                snackbarHostState.showSnackbar("Authentification requise")
                                isCreating = false
                                return@launch
                            }
                            val dto = CreateChildRequest(
                                nom = nom.trim(),
                                prenom = prenom.trim(),
                                dateNaissance = dateStr ?: "",
                                photoProfil = photoUrl
                            )
                            vm.createChild(pid, dto) { result ->
                                scope.launch {
                                    result.onSuccess { resp ->
                                        try {
                                            photoUri?.let { uri ->
                                                try {
                                                    // Photo upload would go here if needed
                                                    // AuthRepository(context).uploadChildPhoto(resp.child.id ?: "", uri)
                                                } catch (e: Exception) {
                                                    Log.w("CreateChild", "Photo upload failed: ${e.message}")
                                                }
                                            }
                                            // Refresh parent data after successful child creation
                                            vm.loadData()
                                            onCreated(
                                                (resp.generatedCredentials?.email ?: "") to (resp.generatedCredentials?.motDePasse ?: "")
                                            )
                                        } catch (e: Exception) {
                                            Log.e("CreateChild", "Error in success handling: ${e.message}")
                                            snackbarHostState.showSnackbar("Enfant créé mais erreur lors de la finalisation")
                                        }
                                    }
                                    result.onFailure { ex ->
                                        Log.e("CreateChild", "Child creation failed: ${ex.message}")
                                        snackbarHostState.showSnackbar(ex.message ?: "Erreur lors de la création")
                                    }
                                }
                            }
                        } finally {
                            isCreating = false
                        }
                    }
                },
                enabled = enabled,
                colors = ButtonDefaults.buttonColors(containerColor = SportyKidsGreen)
            ) {
                if (isCreating) {
                    CircularProgressIndicator(
                        modifier = Modifier.size(16.dp),
                        strokeWidth = 2.dp,
                        color = Color.White
                    )
                    Spacer(Modifier.width(8.dp))
                }
                Text("Créer")
            }
        },
        dismissButton = {
            TextButton(onClick = { if (!isCreating) onDismiss() }) {
                Text("Annuler", color = AccentOrange)
            }
        }
    )
}

// Simple wrapper for MainScreen compatibility
// Wrapper with NavHost for internal navigation within the "Mon Enfant" tab
@Composable
fun MonEnfantScreen(onLogout: () -> Unit = {}) {
    val context = LocalContext.current
    val application = context.applicationContext as android.app.Application

    // Create NavController for this section
    val navController = androidx.navigation.compose.rememberNavController()

    // Create ViewModel for Parent Screen
    val vm: ParentHomeViewModel = composeViewModel(
        factory = androidx.lifecycle.ViewModelProvider.AndroidViewModelFactory.getInstance(application)
    )

    NavHost(navController = navController, startDestination = "home") {

        // Home Screen (List of children and suvies)
        composable("home") {
            ParentScreen(
                navController = navController,
                vm = vm,
                onLogout = {
                    val authRepo = AuthRepository(context)
                    kotlinx.coroutines.CoroutineScope(kotlinx.coroutines.Dispatchers.Main).launch {
                        authRepo.logout()
                        Log.d("MonEnfantScreen", "Logout requested from helper")
                        onLogout()
                    }
                }
            )
        }

        // Chat List
        composable("chat_list") {
            ContactListScreen(navController = navController)
        }

        // Chat Detail
        composable("chat/{userId}") { backStackEntry ->
            val userId = backStackEntry.arguments?.getString("userId") ?: ""
            ChatScreen(navController = navController, userId = userId)
        }

        // Suivi/Child Detail
        composable("$PRESENCE_DETAIL_ROUTE/{childId}") { backStackEntry ->
            val childId = backStackEntry.arguments?.getString("childId") ?: ""
            SuiviDetailScreen(navController = navController, childId = childId)
        }

        // AI Summary
        composable("ai_summary/{childId}") { backStackEntry ->
            val childId = backStackEntry.arguments?.getString("childId") ?: ""
            SuiviAiSummaryScreen(navController = navController, childId = childId)
        }
    }
}
